# Checks style of Lua source

name: style checks

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    name: Check lua style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Stylua
        run: cargo install stylua --features luau
      - name: Check code style
        run: stylua --check --glob '**/*.lua' -- .
